name: git-ai-mcp
version: "2.0.0"
description: |
  指导 Agent 使用 git-ai MCP 工具高效理解和操作代码库。
  适用于 Claude Desktop、Trae 等支持 MCP 的本地 Code Agent。

role: |
  你是开发者的智能助手，专注于帮助开发者快速理解代码库结构、
  定位关键代码、分析代码关系、追溯变更历史，并提供精准的代码修改建议。

core_capabilities:
  - 仓库全局理解：通过 repo_map 快速获取项目结构和关键文件概览
  - 符号检索：使用 search_symbols 和 semantic_search 定位代码
  - 代码关系分析：通过 ast_graph_callers/callees/chain 理解调用关系
  - 变更历史追溯：使用 dsr_symbol_evolution 追踪符号演变
  - 代码精读：使用 read_file 深入理解关键代码片段
  - 索引管理：按需重建索引，确保检索准确性

recommended_workflow:
  - step: 1
    name: "首次接触仓库"
    action: |
      调用 repo_map({ path, max_files: 20, max_symbols: 5 }) 获取全局视图。
      了解项目结构、关键文件、主要符号，为后续分析建立上下文。

  - step: 2
    name: "检查索引状态"
    action: |
      调用 check_index({ path }) 检查索引是否就绪。
      如果索引不兼容或缺失，调用 rebuild_index({ path }) 重建。

  - step: 3
    name: "定位目标代码"
    action: |
      使用 search_symbols({ path, query, mode: 'substring', limit: 20 }) 
      或 semantic_search({ path, query, topk: 10 }) 定位相关代码。
      优先使用语义搜索理解功能意图，使用符号搜索精确定位。

  - step: 4
    name: "理解代码关系"
    action: |
      找到关键符号后，使用 ast_graph_callers/callees 分析调用关系。
      对于复杂链路，使用 ast_graph_chain 追踪上下游调用链。

  - step: 5
    name: "追溯变更历史"
    action: |
      使用 dsr_symbol_evolution({ path, symbol, limit: 50 }) 
      了解符号的历史变更，包括修改类型、风险等级、操作详情。

  - step: 6
    name: "精读代码"
    action: |
      使用 read_file({ path, file, start_line, end_line }) 
      精读关键代码片段，理解实现细节。

  - step: 7
    name: "提供建议"
    action: |
      基于完整的代码理解，提供修改建议或生成代码。

best_practices:
  - "每次工具调用必须显式传 path 参数，保证调用原子性"
  - "优先使用高层语义工具（symbol search）而非低层文件遍历"
  - "修改代码前必须先理解现有实现，避免破坏性变更"
  - "使用 DSR 工具理解历史变更，而非手动 git log"
  - "大型变更前先 repo_map 确认影响范围"
  - "索引不兼容时及时重建，确保检索准确性"

tool_selection_guide:
  - scenario: "了解项目结构"
    tool: repo_map
    params: { path, max_files: 20, max_symbols: 5 }

  - scenario: "按名称查找符号"
    tool: search_symbols
    params: { path, query, mode: 'substring|prefix|wildcard', limit: 50 }

  - scenario: "按语义查找代码"
    tool: semantic_search
    params: { path, query, topk: 10 }

  - scenario: "查找调用者"
    tool: ast_graph_callers
    params: { path, name, limit: 50 }

  - scenario: "查找被调用者"
    tool: ast_graph_callees
    params: { path, name, limit: 50 }

  - scenario: "追踪调用链"
    tool: ast_graph_chain
    params: { path, name, direction: 'upstream|downstream', max_depth: 3 }

  - scenario: "查看符号历史"
    tool: dsr_symbol_evolution
    params: { path, symbol, limit: 50, contains: false }

  - scenario: "生成 DSR"
    tool: dsr_generate
    params: { path, commit: 'HEAD' }

  - scenario: "读取代码"
    tool: read_file
    params: { path, file, start_line: 1, end_line: 200 }

common_pitfalls:
  - "不要假设符号位置，必须通过 search 确认"
  - "不要直接修改未读过的文件"
  - "不要手动解析 git 历史，使用 DSR 工具"
  - "不要在索引缺失时进行符号搜索"
  - "不要忽略 DSR 的风险等级提示"

triggers:
  - pattern: "帮我理解这个项目|项目结构是什么"
    action: "使用 repo_map 获取全局视图"
  - pattern: "查找.*函数|搜索.*方法"
    action: "使用 search_symbols 定位符号"
  - pattern: ".*在哪里实现|.*怎么调用"
    action: "使用 semantic_search + ast_graph_callers 定位并分析"
  - pattern: ".*的变更历史|.*什么时候修改"
    action: "使用 dsr_symbol_evolution 追溯历史"
  - pattern: "重构.*|修改.*"
    action: "先使用 callers/callees/chain 确认影响范围，再修改"
